export const team = [
  {
    name: "Sajjan Singh Yadav",
    post: "Founder",
    phone: "9891544141",
    email: "legalhelp@ncrlawassociate.com",
    imgUrl: "/sajjanSingh.jpg",
    startDate: "1982",
    description: [
      "Since the inception of law firm we have handled and argued a wide range of Criminal cases at all stages and various kinds of Civil Matters such as Suits,  Writs, Appeals, Revisions, Arbitration Petitions, Contractual Law, Company Law, Family Law, Constitution of India, Securitization Law, Service Law, Labour Law etc. ",
      "Joined as Assistant District Attorney/Assistant Public Prosecutor/Govt. Pleader in Prosecution Department, Govt. of Haryana in (April 1992). ",
      "After 7 years as APP, notified as Public Prosecutor by the Govt. of Haryana (1999)",
      "Prompoted as Deputy District Attorney in the Prosecution Department by the Govt. of Haryana in August, 2010.",
      "During my tenure in prosecution department, conducted all types of trials i.e. heinous crimes and murder cases before the court of Hon’ble Session Judge/ASJ; the work/trial assigned during said tenure and also represented States in all important civil cases including arbitration on behalf of States before the Hon’ble Court of District Judge/Addl. District Judge.",
      "Sought voluntary retirement from Govt. of Haryana and started practice as an Advocate (in August 2012).",
    ],
  },
  {
    name: "Tarun Yadav",
    post: "CoFounder",
    phone: "9779151774",
    email: "tarun154.yadav@yahoo.com",
    imgUrl: "/tarunYadav.jpeg",
    startDate: "2011",
    description: [
      "Practicing since 2011, Advocate he is a seasoned legal professional known for his unwavering dedication to justice and precision in legal strategy. Based at the High Court of Punjab and Haryana, he has earned a reputation for delivering results across a broad spectrum of legal domains, including matrimonial disputes, criminal trials and appeals, civil suits, labour matters, and arbitration proceedings.",
      "With over a decade of courtroom experience, he approaches each case with a judicious blend of legal insight and procedural command. His sharp legal instincts and clarity of argumentation have consistently earned him the trust of clients and respect among peers. Whether navigating the intricacies of a family dispute or contesting a complex civil or criminal matter, his focus remains firmly on time-bound, result-oriented advocacy.",
      "Known for his integrity, professionalism, and client-centric approach, he stands as a dependable pillar in the High Court litigation landscape.",
    ],
  },

  {
    name: "Rahul Yadav",
    post: "CoFounder",
    phone: "9910731889",
    email: "rahulyadavadv1987@gmail.com",
    imgUrl: "/rahulYadav.jpg",
    startDate: "2011",
    description: [
      "With over a decade of experience in the legal profession, Advocate [Name] has been actively practicing since 2011, offering expert legal counsel and representation in a wide range of matters. His expertise spans across matrimonial disputes, criminal defense, civil litigation, labour law, and arbitration.",
      "Known for his sharp legal acumen and strategic approach, he has successfully represented clients before various courts and tribunals across India. His commitment to timely and effective justice delivery sets him apart, ensuring that clients receive practical solutions within a structured timeframe.",
      "Advocate [Name] combines deep knowledge of substantive and procedural law with a results-driven mindset, making him a trusted legal advisor for both individuals and corporate clients.",
    ],
  },
  {
    name: "Lokesh Yadav",
    post: "Associates",
    phone: "9991636649",
    email: "advlokeshrao@gmail.com",
    imgUrl: "/LokeshYadav.jpeg",
    startDate: "2016",
    description: [
      "As an Advocate he is practicing since 2016, is a committed legal professional offering comprehensive legal services across the trial courts of Haryana. With a strong command over multiple branches of law—including criminal defense, matrimonial disputes, civil litigation, labour matters, and arbitration—he brings a client-focused, result-driven approach to every case.",
      "Known for his clarity in legal reasoning and deep understanding of procedural law, he has built a reputation for resolving complex disputes efficiently and effectively. He believes in time-bound justice and is dedicated to providing practical, honest, and strategic counsel to individuals and businesses alike.",
      "His practice stands out for its adaptability across diverse legal issues, keen attention to detail, and relentless advocacy tailored to the unique circumstances of each client. Whether you’re facing a sensitive family matter, a criminal accusation, or a contractual dispute, he ensures your legal journey is handled with professionalism, transparency, and commitment.",
    ],
  },
  {
    name: "Ashutosh Anand",
    post: "Associates",
    phone: "9899099458",
    email: "adv.ashutosh09@gmail.com",
    imgUrl: "/ashutoshAnand.png",
    startDate: "2018",
    description: [
      "Ashutosh Anand is a dedicated legal professional with a proven track record in providing comprehensive legal counsel, regulatory guidance, and strategic insights to clients across diverse industries. Having worked with PricewaterhouseCoopers Private Limited (PwC) for 7 years, Ashutosh has an extensive professional experience in the areas of regulatory compliance, public policy, and investment advisory matters. His focus areas were Public Policy and Regulatory/ Compliance matters in the areas of Foreign Direct Investment Policy, Foreign Exchange Management Act, and Corporate Laws. ",
      "He has experience with client secondment with the Department for Promotion of Industry and Internal Trade (DPIIT) for a strategic public policy project related to 'Ease of Doing Business' in India with special focus on labor laws. Ashutosh is currently enrolled as an advocate and practicing in Delhi and Gurgaon Trial Courts in civil and criminal laws. He has successfully represented in Arbitration, Bail, N.I. Act Domestic Violence & Delhi Excise Act matters.",
      "Ashutosh has successfully completed LL.M in Corporate and Financial Laws from O.P. Jindal Global Law School. Ashutosh is a Law Graduate from the Faculty of Law, University of Delhi, and have also successfully completed PG Diploma in Corporate Law & Management from Indian Law Institute, New Delhi.",
    ],
  },
  {
    name: "Yudhisthir Yadav",
    post: "Associates",
    phone: "7015804793",
    email: "advyudhisthiryadav@gmail.com",
    imgUrl: "/kuku5.png",
    startDate: "2023",
    description: [
      "An advocate by profession, he is known for his dynamic legal practice, representing clients across India and internationally in criminal, civil, matrimonial disputes, labour, arbitration, and real estate matters. A graduate of the esteemed Campus Law Centre, University of Delhi, he brings a sharp legal mind, strategic thinking, and a commitment to client advocacy.",
      "He has a keen interest in Intellectual Property Rights (IPR) and legal matters involving complex technical dimensions, where his ability to bridge law and technology adds significant value. Before entering the legal field, he earned a degree in Electrical Engineering, which equips him with analytical rigor and a structured problem-solving approach.",
      "His multidisciplinary background enables him to approach intricate legal issues with clarity and precision, particularly in cases at the intersection of law, innovation, and technology.",
    ],
  },
];
