export const team = [
  {
    name: "Sajjan Singh Yadav",
    post: "Founder",
    phone: "9891544141",
    email: "legalhelp@ncrlawassociate.com",
    imgUrl: "/sajjanSingh.jpg",
    startDate: "1982",
    description: [
      "Since the inception of law firm we have handled and argued a wide range of Criminal cases at all stages and various kinds of Civil Matters such as Suits,  Writs, Appeals, Revisions, Arbitration Petitions, Contractual Law, Company Law, Family Law, Constitution of India, Securitization Law, Service Law, Labour Law etc. ",
      "Joined as Assistant District Attorney/Assistant Public Prosecutor/Govt. Pleader in Prosecution Department, Govt. of Haryana in (April 1992). ",
      "After 7 years as APP, notified as Public Prosecutor by the Govt. of Haryana (1999)",
      "Promoted as Deputy District Attorney in the Prosecution Department by the Govt. of Haryana in August, 2010.",
      "During my tenure in prosecution department, conducted all types of trials i.e. heinous crimes and murder cases before the court of Hon’ble Session Judge/ASJ; the work/trial assigned during said tenure and also represented States in all important civil cases including arbitration on behalf of States before the Hon’ble Court of District Judge/Addl. District Judge.",
      "Sought voluntary retirement from Govt. of Haryana and started practice as an Advocate (in August 2012).",
    ],
  },
  {
    name: "Tarun Yadav",
    post: "Team Member",
    phone: "9779151774",
    email: "tarun154.yadav@yahoo.com",
    imgUrl: "/tarunYadav.jpeg",
    startDate: "2011",
  },
  {
    name: "Rahul Yadav",
    post: "Team Member",
    phone: "9910731889",
    email: "rahulyadavadv1987@gmail.com",
    imgUrl: "/rahulYadav.jpg",
    startDate: "2011",
  },
  {
    name: "Lokesh Yadav",
    post: "Team Member",
    phone: "9991636649",
    email: "advlokeshrao@gmail.com",
    imgUrl: "/LokeshYadav.jpeg",
    startDate: "2016",
  },
  {
    name: "Ashutosh Anand",
    post: "Team Member",
    phone: "9899099458",
    email: "adv.ashutosh09@gmail.com",
    imgUrl: "/ashutoshAnand.png",
    startDate: "2018",
    description: [
      "Ashutosh Anand is a dedicated legal professional with a proven track record in providing comprehensive legal counsel, regulatory guidance, and strategic insights to clients across diverse industries. Having worked with PricewaterhouseCoopers Private Limited (PwC) for 7 years, Ashutosh has an extensive professional experience in the areas of regulatory compliance, public policy, and investment advisory matters. His focus areas were Public Policy and Regulatory/ Compliance matters in the areas of Foreign Direct Investment Policy, Foreign Exchange Management Act, and Corporate Laws. ",
      "He has experience with client secondment with the Department for Promotion of Industry and Internal Trade (DPIIT) for a strategic public policy project related to 'Ease of Doing Business' in India with special focus on labor laws. Ashutosh is currently enrolled as an advocate and practicing in Delhi and Gurgaon Trial Courts in civil and criminal laws. He has successfully represented in Arbitration, Bail, N.I. Act Domestic Violence & Delhi Excise Act matters.",
      "Ashutosh has successfully completed LL.M in Corporate and Financial Laws from O.P. Jindal Global Law School. Ashutosh is a Law Graduate from the Faculty of Law, University of Delhi, and have also successfully completed PG Diploma in Corporate Law & Management from Indian Law Institute, New Delhi.",
    ],
  },
  {
    name: "Yudhisthir Yadav",
    post: "Team Member",
    phone: "7015804793",
    email: "advyudhisthiryadav@gmail.com",
    imgUrl: "/kuku5.png",
      startDate: "2023",
    
  },
];
